### ISSUE TITLE
Make Feedback File Public for Testing

### ISSUE THREAD

**Issue by hayleepierce** [GatorEducator/cellveyor#14]
@gkapfham

**Comment by gkapfham** [comment]
Hi @hayleepierce, thanks for raising this issue. I've thought a lot about this issue and I currently have the view that I likely cannot share all of my feedback templates. With that said, I think that I could share a few examples. Do you think that these can go inside of this repository? Or, do we need to create a separate repository? Let me know what you prefer.

**Comment by hayleepierce** [comment]
@gkapfham, I think it would be best to have them inside this repository, for the sake of easy access. I also think they could be used by the users of the tool for a template, as long as you are okay with them being used for more than just testing.

**Comment by gkapfham** [comment]
Hi @hayleepierce, I think that what I will do for this issue is to post some sample YML files in the issue tracker. I will make it clear that they are general purpose and not specific to a certain course. Then you can create a PR and merge them into the repository in an appropriate directory. My main concern is that it is better if I do not include all examples of the various types of feedback that I include --- but I think that including some representative examples should be okay. Let me know if this will work or if you have other ideas for the best plan!

**Comment by hayleepierce** [comment]
@gkapfham, That will work. Thank you!

**Comment by hayleepierce** [comment]
@gkapfham Here is a ping reminder to share the example feedback that can be used for manual testing. Thank you!
